//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGameLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int VideoGameId { get; set; }
        public string Title { get; set; }
        public string Platform { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public string GameDescription { get; set; }
        public string Publisher { get; set; }
        public string Developer { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    
        public virtual Platforms Platforms { get; set; }
    }
}
