//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGameLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platforms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Platforms()
        {
            this.Games = new HashSet<Games>();
        }
    
        public int PlatformId { get; set; }
        public string PlatformName { get; set; }
        public string Brand { get; set; }
        public string ConsoleType { get; set; }
        public int ConsoleTypeId { get; set; }
    
        public virtual ConsoleTypes ConsoleTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Games> Games { get; set; }
    }
}
